{
 "title": "API statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API methods",
   "type": "logs",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "   {service=\"backend\"} |= \"Method:\" | regexp \"Method: (?P<method>\\\\w+)\" | line_format \"{{.method}}\""
    }
   ]
  },
  {
   "title": "API Endpoints",
   "type": "logs",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "   {service=\"backend\"} |= \"URL:\" | regexp \"URL: (?P<url>\\\\S+)\" | line_format \"{{.url}}\""
    }
   ]
  },
  {
   "title": "Authentication Errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"backend\"} |~ \"Login error|Registration error|Invalid credentials\""
    }
   ]
  },
  {
   "title": "Database Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"backend\"} |~ \"error|Error|ERROR\""
    }
   ]
  }
 ]
}